@FYTER-KA-BAAP
TERI BAHAN KI CHUT KA BHOSDA
TERI AMMI KI GAND ME MERA LUND
TERI AMMI KI CHUCHI MASLU MADARCHOD
TERI BAHN KI CHIKNI CHUT KO FADKE RAKH DUNGA
TERI BHAN KI SEXY CHUT KA BHOSDA BNAU
TERI BHAN KI CHUCHI KO PI JAUNGA
MADARCHOD MERE LUND KE PAIDAISH
TERI BHAN KI GAND KO DIWAR PE THOKKE CHODUNGA
TERI BHAN KI GAND PE THAPPAR MAARKE UCHHAL UCHHAL KE CHODUNGA
